### ISSUE TITLE
Unable to Decode Float elements in RGB1 Images

### ISSUE THREAD

**Issue by wcork** [epics-base/epicsCoreJava#49]
Error stack is large. The image data was dumped to the console at the acquisition rate:
```
2019-02-28 15:47:27 WARNING [org.phoebus.ui.javafx.BufferUtil] Skipping image update
2019-02-28 15:47:27 SEVERE [org.phoebus.ui.application.PhoebusApplication] UI Updates resume
2019-02-28 15:47:56 WARNING [org.phoebus.pv] Cannot handle update for pva://testcam:Pva1:Image
java.lang.Exception: Cannot decode NTNDArray type of value float[]  [ALL THE IMAGE DATA]
	at org.phoebus.pv.pva.ImageDecoder.decode(ImageHelper.java:207)
	at org.phoebus.pv.pva.PVStructureHelper.getVType(PVStructureHelper.java:119)
	at org.phoebus.pv.pva.PVA_PV.handleValueUpdate(PVA_PV.java:208)
	at org.phoebus.pv.pva.PVA_PV.monitorEvent(PVA_PV.java:233)
	at org.epics.pvaccess.client.impl.remote.ChannelMonitorImpl$MonitorStrategyQueue.response(ChannelMonitorImpl.java:358)
	at org.epics.pvaccess.client.impl.remote.ChannelMonitorImpl.normalResponse(ChannelMonitorImpl.java:581)
	at org.epics.pvaccess.client.impl.remote.ChannelMonitorImpl.response(ChannelMonitorImpl.java:617)
	at org.epics.pvaccess.client.impl.remote.handlers.DataResponseHandler.handleResponse(DataResponseHandler.java:46)
	at org.epics.pvaccess.client.impl.remote.ClientResponseHandler.handleResponse(ClientResponseHandler.java:108)
	at org.epics.pvaccess.impl.remote.tcp.BlockingTCPTransport.processApplicationMessage(BlockingTCPTransport.java:270)
	at org.epics.pvaccess.impl.remote.codec.AbstractCodec.processReadNormal(AbstractCodec.java:186)
	at org.epics.pvaccess.impl.remote.codec.AbstractCodec.processRead(AbstractCodec.java:98)
	at org.epics.pvaccess.impl.remote.codec.impl.BlockingAbstractCodec.receiveThread(BlockingAbstractCodec.java:121)
	at org.epics.pvaccess.impl.remote.codec.impl.BlockingAbstractCodec$1.run(BlockingAbstractCodec.java:101)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This occurred when using an areaDetector simulator and Phoebus using Float16 and Float32 elements in RGB1 images.

**Comment by shroffk** [comment]
We were able to debug part of the issue to org.phoebus.pv
https://github.com/shroffk/phoebus/pull/566

**Comment by kasemir** [comment]
Should be fixed, please re-open if issue still persists.
