### ISSUE TITLE
gpclient tests are failing for Java 11

### ISSUE THREAD

**Issue by ralphlange** [epics-base/epicsCoreJava#60]
Lots of
```
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ gpclient-core ---
[INFO] Surefire report directory: /home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/gpclient/gpclient-core/target/surefire-reports

-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running org.epics.gpclient.PVEventRecorderTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.484 sec
Running org.epics.gpclient.datasource.DataSourceImplementationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.112 sec
Running org.epics.gpclient.PVEventTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running org.epics.gpclient.ActiveRateDecouplerTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.027 sec
Running org.epics.gpclient.LatestValueCollectorTest
Tests run: 7, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.85 sec <<< FAILURE!
updateValue1(org.epics.gpclient.LatestValueCollectorTest) Time elapsed: 0.578 sec <<< ERROR!
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface java.util.function.Consumer.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java : 11
JVM vendor name : Oracle Corporation
JVM vendor version : 11.0.3+7-LTS
JVM name : OpenJDK 64-Bit Server VM
JVM version : 11.0.3+7-LTS
JVM info : mixed mode, sharing
OS name : Linux
OS version : 3.10.0-693.rt56.617.el7.x86_64


Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
at org.epics.gpclient.LatestValueCollectorTest.updateValue1(LatestValueCollectorTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
...
```

**Comment by shroffk** [comment]
I have updated the core stack on the release-7.0 branch

Here are the successful travis builds of the branch
https://travis-ci.org/epics-base/epicsCoreJava/builds/583176964

**Comment by shroffk** [comment]
@ralphlange can this be closed??

**Comment by ralphlange** [comment]
Yes, sure.
